apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-1gb
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
